### ISSUE TITLE
Add Zcash sapling support

### ISSUE THREAD

**Issue by MarkLTZ** [trezor/bitcoinjs-trezor#8]
Hi!

when zcash sapling support will be added?

Thanks,
Mark

**Comment by prusnak** [comment]
Use https://github.com/BitGo/bitgo-utxo-lib/

**Comment by MarkLTZ** [comment]
I know about bitgo-utxo-lib, but many software I use are build for bitcoinjs-lib so fixing they to use bitcoinjs-trezor is the fastest way.

Why this answer? Is this fix not on roadmap? Is bitcoinjs-trezor still maintained?

**Comment by prusnak** [comment]
The answer is above. Don't use our fork.

**Comment by karelbilek** [comment]
bitgo-utxo-lib has almost the same API as bitcoinjs-lib and is better maintained. Sorry

**Comment by MarkLTZ** [comment]
I know that, but many software I use are build for bitcoinjs-lib so patching they to use bitcoinjs-trezor is the fastest way. Using bitgo-utxo-lib could be very nice and better but it require a lot of time to patch them.
